<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart 
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'hosts_fileparser' => '/lib/Hosts/FileParser.php',
                'hosts_fileparsertest' => '/../test/lib/Hosts/FileParserTest.php',
                'hswitch' => '/lib/Hswitch.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd